import { browser } from 'wxt/browser';
import { PLAY_CHIME_MESSAGE } from '@/utils/constants';

// Service workers cannot play audio, so the chime plays in an offscreen
// document. See ADR-005.

/** Where WXT builds entrypoints/offscreen/index.html. */
const OFFSCREEN_PATH = '/offscreen.html';
/** In public/, generated by scripts/generate-assets.mjs. */
const CHIME_PATH = '/chime.wav';

/** The in-flight createDocument call, if any. */
let creating: Promise<void> | null = null;

/**
 * Chrome allows one offscreen document per extension and closes an
 * audio-only one about 30 seconds after the sound stops, so it is checked
 * for, and recreated if needed, before every chime.
 */
async function ensureOffscreenDocument(): Promise<void> {
  const contexts = await browser.runtime.getContexts({ contextTypes: ['OFFSCREEN_DOCUMENT'] });
  if (contexts.length > 0) return;

  // Two alarms firing together must not both try to create the document.
  creating ??= browser.offscreen
    .createDocument({
      url: OFFSCREEN_PATH,
      reasons: ['AUDIO_PLAYBACK'],
      justification: 'Play the gentle reminder chime.',
    })
    .finally(() => {
      creating = null;
    });
  await creating;
}

/** Called from the service worker. A failed chime never blocks a reminder. */
export async function playChime(): Promise<void> {
  try {
    await ensureOffscreenDocument();
    await browser.runtime.sendMessage({ type: PLAY_CHIME_MESSAGE });
  } catch (error) {
    console.warn('Hydrate.ly: could not play the chime.', error);
  }
}

/** Called from the offscreen document: plays the chime when asked. */
export function listenForChime(): void {
  const audio = new Audio(browser.runtime.getURL(CHIME_PATH));
  browser.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    // Other extension pages share this message channel; ignore their traffic.
    if ((message as { type?: unknown } | null)?.type !== PLAY_CHIME_MESSAGE) return;
    // Water and break reminders can land together; one chime is enough.
    if (audio.paused || audio.ended) {
      audio.currentTime = 0;
      audio.play().catch((error) => console.warn('Hydrate.ly: chime playback failed.', error));
    }
    // Reply so the sender's promise settles instead of reporting a closed port.
    sendResponse({ ok: true });
  });
}
