import { browser } from 'wxt/browser';
import type { NotificationContent, ReminderKind } from '@/types';

// One fixed id per kind, so a new reminder replaces the old one instead of
// stacking up.
const NOTIFICATION_ID: Record<ReminderKind, string> = {
  water: 'hydrately:water',
  break: 'hydrately:break',
};

/** In public/, generated by scripts/generate-assets.mjs. */
const ICON_PATH = {
  water: '/notifications/water.png',
  break: '/notifications/break.png',
} as const;

/** Maps a notification back to its reminder; null if it is not one of ours. */
function kindOf(notificationId: string): ReminderKind | null {
  if (notificationId === NOTIFICATION_ID.water) return 'water';
  if (notificationId === NOTIFICATION_ID.break) return 'break';
  return null;
}

/**
 * Shows a reminder with two action buttons. `persistent` keeps it on screen
 * until the user acts; otherwise it is a banner that fades on its own.
 * Always silent: the optional chime is ours (services/chime.ts).
 */
export async function showReminder(
  kind: ReminderKind,
  content: NotificationContent,
  persistent: boolean,
): Promise<void> {
  await browser.notifications.create(NOTIFICATION_ID[kind], {
    type: 'basic',
    iconUrl: browser.runtime.getURL(ICON_PATH[kind]),
    title: content.title,
    message: content.message,
    // Chrome shows at most two buttons; their order is the index that
    // onButtonClicked reports.
    buttons: content.buttons.map((title) => ({ title })),
    requireInteraction: persistent,
    silent: true,
    // Priority is only a hint to the OS; persistent reminders ask for the highest.
    priority: persistent ? 2 : 0,
  });
}

/** Removes the reminder from the screen and the notification centre. */
export async function clearReminder(kind: ReminderKind): Promise<void> {
  await browser.notifications.clear(NOTIFICATION_ID[kind]);
}

/** `buttonIndex` 0 is the primary action, 1 is Snooze. */
export function onReminderButton(callback: (kind: ReminderKind, buttonIndex: number) => void): void {
  browser.notifications.onButtonClicked.addListener((notificationId, buttonIndex) => {
    const kind = kindOf(notificationId);
    if (kind) callback(kind, buttonIndex);
  });
}

/** The notification body was clicked, outside the buttons. */
export function onReminderClick(callback: (kind: ReminderKind) => void): void {
  browser.notifications.onClicked.addListener((notificationId) => {
    const kind = kindOf(notificationId);
    if (kind) callback(kind);
  });
}
